# Generated by Django 4.2.4 on 2023-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(help_text='From Email', max_length=254)),
                ('to_email', models.EmailField(help_text='To Email', max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
